CREATE database `matricula`;

use `matricula`;

CREATE TABLE USUARIO (
USER VARCHAR(12),
PASSWORD VARCHAR(255),
TIPO INT NOT NULL,
PRIMARY KEY (USER)

);

CREATE TABLE ESTUDIANTE (
CEDULA VARCHAR(12) NOT NULL,
NOMBRE VARCHAR(255),
APELLIDO VARCHAR(255),
CORREO VARCHAR(255),
TELEFONO INT,
COD_CARRERA VARCHAR(12),
constraint CEDULA foreign key (CEDULA) references USUARIO (USER),
PRIMARY KEY (CEDULA)
);


CREATE TABLE PROFESOR (
CEDULA VARCHAR(12) NOT NULL,
NOMBRE VARCHAR(255),
APELLIDO VARCHAR(255),
CORREO VARCHAR(255),
TELEFONO INT,
constraint CEDULA foreign key (CEDULA) references USUARIO (USER),
PRIMARY KEY (CEDULA)
);

CREATE TABLE ADMINISTRADOR (
    CEDULA VARCHAR(12) NOT NULL,
  NOMBRE VARCHAR(255),
  APELLIDO VARCHAR(255),
  CORREO VARCHAR(255),
  TELEFONO INT,
  constraint CEDULA foreign key (CEDULA) references USUARIO (USER),
  PRIMARY KEY (CEDULA)
);

CREATE TABLE MATRICULADOR(
  CEDULA VARCHAR(12) NOT NULL,
  NOMBRE VARCHAR(255),
  APELLIDO VARCHAR(255),
  CORREO VARCHAR(255),
  TELEFONO INT,
  constraint CEDULA foreign key (CEDULA) references USUARIO (USER),
  PRIMARY KEY (CEDULA)
);

CREATE TABLE CARRERA (
CODIGO VARCHAR(12) NOT NULL,
NOMBRE VARCHAR(255) NOT NULL,
PRIMARY KEY (CODIGO)
);

CREATE TABLE CURSO (
CODIGO VARCHAR(12) NOT NULL,
NOMBRE VARCHAR(255),
CREDITOS INT,
H_SEMANALES INT,
COD_CARRERA VARCHAR(12),
NUM_CICLO INT NOT NULL,
constraint COD_CARRERA foreign key (COD_CARRERA) references CARRERA (CODIGO),
PRIMARY KEY (CODIGO)
);

CREATE TABLE GRUPO (
NUMERO INT NOT NULL,
ID_PROF VARCHAR(12),
COD_CURSO VARCHAR(12),
constraint COD_CURSO foreign key (COD_CURSO) references CURSO (CODIGO),
constraint ID_PROF foreign key (ID_PROF) references PROFESOR (CEDULA)
);

CREATE TABLE CICLO (
ID INT NOT NULL,
ANNO INT NOT NULL,
NUM_CICLO INT NOT NULL,
FECHA_INICIO VARCHAR(10),
FECHA_FINAL VARCHAR(10),
PRIMARY KEY (ID)
);








